
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    privileged: true
    user: root
    restart: always
    # network_mode: host
    ports:
      - '30003:8080'    # Jenkins Web UI
      - "50000:50000"   # For Jenkins agent connections
    volumes:
      - /home/gray.lin/.ssh/:/root/.ssh/
      - /home/gray.lin/OSPath/Docker/aicamera_plus_box/:/root/aicamera_plus_box/
      - /usr/local/bin/docker-compose:/usr/bin/docker-compose
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/disk2/yocto_build_folder/docker/jenkins/jenkins_home:/var/jenkins_home
      - /mnt/disk2/yocto_build_folder/docker:/home

    environment:
      - TZ=Asia/Taipei
      #- JAVA_OPTS=-Dmail.debug=true
      #- JAVA_OPTS=-Djenkins.install.runSetupWizard=false  # Optional: skip setup wizard
      #- JAVA_OPTS=-Dhudson.security.HudsonPrivateSecurityRealm.ID_REGEX=[a-zA-Z0-9_.@-]+

